# Configure main menu and social menu
#[[main]]
#identifier = "home"
#name = "Home"
#url = "/"
#[main.params]
#icon = "home"
#newtab = true

## Icons are from https://tabler.io/icons

[[social]]
    identifier = "github"
    name       = "GitHub"
    url        = "https://github.com/dinoesau"

    [social.params]
        icon = "brand-github"

[[social]]
    identifier = "linkedin"
    name       = "LinkedIn"
    url        = "https://www.linkedin.com/in/esaum/"

    [social.params]
        icon = "brand-linkedin"

# mail social contact@esau.com.mx
[[social]]
    identifier = "email"
    name       = "Email"
    url        = "mailto:contact@esau.com.mx"

    [social.params]
        icon = "mail"


